SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 700
TITLE = "The Heroic V"
START_LOCATION_X = 64
START_LOCATION_Y = 128
MAX_LIVES = 5
# File path to riddle folder
CHARACTER_SCALE = 1
TILE_SCALE = .5
COIN_SCALE = .5
MOVEMENT_SPEED = 5
GRAVITY = 1
JUMP_SPEED = 20